@extends("layouts.blank")

@section('content') 
    <div id="common-home">

        <div class="container">

            <div class="row">

                <h4>Sellers Policy</h4>

                <h5>Terms of Use</h5>

                <p>This document is an electronic record in terms of Information Technology Act, 2000 (“IT Act, 2000”), the applicable rules thereunder and the provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.</p>

            </div>

        </div>

    </div>
@endsection


@push('styles')
@endpush