@extends("layouts.blank")

@section('content') 
    <div id="common-home">

        <div class="container">

            <div class="row">

                <h4>Sellers Policy</h4>

                <h5>Terms of Use</h5>

                <p>This document is an electronic record in terms of Information Technology Act, 2000 (“IT Act, 2000”), the applicable rules thereunder and the provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.</p>
                <p>This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries Guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access to or usage of<br>
                <a href="#">www.maahirbharat.com </a>website, and The IT Rules 2021.</p> 
                </p>
                <p>The domain name <b>www. maahirbharat.com</b>, including the related mobile site and mobile application as well as the seller portal seller. <a href="#">www.maahirbharat.com</a> (hereinafter referred to as “Platform”) is owned and operated as an initiative taken by ABC training solutions, a company incorporated under the Companies Act, 1956, with its registered office at Pune</p>
                <p>For the purpose of the Terms of Use (hereinafter it is referred as Terms) wherever the context so requires, ‘you’ and ‘your’ shall relate to any natural or legal person who has agreed to become a seller on the Platform by providing registration data while registering on the Platform using computer systems. The word ‘user’ shall collectively imply a seller, a buyer, and any visitor on the Platform and the terms ‘we’, ‘us’ and ‘our’ shall mean Maahir Bharat.</p>
                <p>When you use any current or future services provided by us through the Platform you will be subject to the rules, guidelines, policies, terms and conditions applicable to such services and they shall be deemed incorporated into the Terms.  We reserve the right, at our sole discretion, to change, modify, add, or remove portions of the Terms at any time. We will notify you through any of the communication modes as mentioned in this Terms in case of any changes or updates to the Terms that materially impact your use of the Platform. Your continued use of the Platform following the changes or updates will mean that you accept and agree to the revisions.</p>
                <p>By visiting this Website you agree to be bound by the terms and conditions of this Privacy Policy.</p>
                <p>By mere use of the Website, you expressly consent to our use and disclosure of your personal information in accordance with this Privacy Policy. This Privacy Policy is incorporated into and subject to the Terms of Use.</p>
                <p>As long as you comply with the Terms, we grant you a personal, non-exclusive, non-transferable, and limited privilege to enter and use the Platform.</p>
                <p>ACCESSING, BROWSING, OR OTHERWISE USING THE PLATFORM INDICATES YOUR AGREEMENT WITH ALL THE TERMS AND CONDITIONS UNDER THE TERMS. PLEASE READ THE TERMS CAREFULLY BEFORE PROCEEDING. By impliedly or expressly accepting the Terms, you also accept and agree to be bound by all ofMahir Bharat’s policies applicable to you, as amended, from time to time. Maahir Bharat is the online destination for small and medium enterprises.</p>
                <p>Maahir Bharat is a unique platform where Seller can list and sell their products supplies, personalized, special, or vintage items and handmade goods, directly to Buyers anywhere in India. For Seller and the Buyers to have a quality successful experience on Maahir Bharat , read and adhere to this policy which include Seller special rights and obligations.</p>

                <ol>
                    <li><b>Collection of Personally Identifiable Information and other Information</b></li>
                    <p>When you use our Website, we collect and store your personal information which is provided by you from time to time. Our primary goal in doing so is to provide you a safe, efficient, smooth and customized experience. This allows us to provide services and features that most likely meet your needs, and to customize our Website to make your experience safer and easier. More importantly, while doing so we collect personal information from you that we consider necessary for achieving this purpose. </p>

                    <li><b>Seller Eligibility</b></li>
                    <p>The use of the Platform is available only to competent persons to contract, who can form legally binding contracts under the Indian Contract Act, 1872, and the persons who are within the meaning of the Indian Contract Act, 1872. Otherwise Maahir Bharat reserves the right to terminate your registration and/or refuse you access to the Platform if it is brought to Maahir Bharat’s notice or discovered that you are under the age of 18 years or an incompetent person to contract. If you register as a business entity, you represent that you are duly authorized by the business entity to accept the Terms and you have the authority to bind the business entity to the Terms.</p>

                    <li><b>Your Account and Registration Obligations</b></li>
                    <p>In the course of your use of the Platform, you agree to furnish your details and information as requested by us from time to time. You shall remain responsible for maintaining confidentiality of this information, as well as your display name, login and password details. You agree that if you provide any untrue, inaccurate, not current, or incomplete information of which we have reasonable grounds to suspect that such information is untrue, inaccurate, not current, incomplete, or not in accordance with the Terms, we shall have the right to suspend or terminate your account on the Platform or indefinitely block you from accessing the Platform.</p>

                    <li><b>Use of Demographic / Profile Data / Your Information</b></li>
                    <ul> 
                        <li>We use personal information to provide the services you request. To the extent we use your personal information to market to you, we will provide you the ability to opt-out of such uses. We use your personal information to resolve disputes; troubleshoot problems; help promote a safe service; collect money; measure consumer interest in our products and services, inform you about online and offline offers, products, services, and updates; customize your experience; detect and protect us against error, fraud and other criminal activity; enforce our terms and conditions; and as otherwise described to you at the time of collection.</li>
                        <li>In our efforts to continually improve our product and service offerings, we collect and analyse demographic and profile data about our users' activity on our Website.</li>
                        <li>We identify and use your IP address to help diagnose problems with our server, and to administer our Website. Your IP address is also used to help identify you and to gather broad demographic information.</li>
                        <li>We will occasionally ask you to complete optional online surveys. These surveys may ask you for contact information and demographic information (like zip code, age, or income level). We use this data to tailor your experience at our Website, providing you with content that we think you might be interested in and to display content according to your preferences.</li>
                    </ul>


                    <li><b>Cookies</b></li>
                    <p>A "cookie" is a small piece of information stored by a web server on a web browser so it can be later read back from that browser. Cookies are useful for enabling the browser to remember information specific to a given user. We place both permanent and temporary cookies in your computer's hard drive. The cookies do not contain any of your personally identifiable information.</p>
                    <li><b>Communications</b></li>
                    <p>When you use the Platform or send emails, other data, information, or communication to us, you agree and understand that you are communicating with us through electronic records and you consent to receive communications via electronic records from us periodically or as and when required. We may communicate with you by email or any other mode of communication, electronic or otherwise.</p>

                    <li><b>Platform for Transaction and Communication</b></li>
                    <p>The Platform is a platform that users utilize to independently meet and interact with one another for their transactions. Maahir Bharat is not and cannot be a party to any transaction or dispute between users on the Platform.</p>
                <!-- </ol> -->
                <h5>Consequently:</h5>
                    <ol type="a">
                        <li>All commercial/contractual terms are offered by you and agreed upon between you seller and buyers alone. The commercial/contractual terms include (without limitation) price, shipping costs, payment methods and terms, date, period, and mode of delivery, and warranties and after-sales services related to products and services. Maahir Bharat does not determine, advice, have any control, or in any way involve itself in the offering or acceptance of such commercial/contractual terms between you and buyers.</li>
                        <li>Maahir Bharat does not make any representations or warranties regarding specifics (such as quality, value, and saleability) of the products or services proposed to be sold, offered to be sold or purchased on the Platform. Maahir Bharat does not implicitly or explicitly support or endorse the sale or purchase of any products and services on the Platform. Maahir Bharat accepts no liability for any errors or omissions of third parties in relation to the products and services.</li>

                        <li>Maahir Bharat is not responsible for any non-performance or breach of any contract between you and buyers. Maahir Bharat cannot and does not guarantee that you and buyers concerned will perform transaction(s) concluded on the Platform. Maahir Bharat shall not and is not required to mediate or resolve disputes or disagreements between you and buyers.</li>
                        <li>Maahir Bharat does not make any representations or warranties regarding item-specifics (such as legal title, creditworthiness, identity, etc.) of any of its users. You are advised to independently verify the bona fides of any particular buyer you choose to deal with on the Platform and use your best judgment in that regard.</li>
                        <li>Maahir Bharat does not at any point in time during a transaction between you and a buyer on the Platform come into or take possession of any of the products or services offered by you, gain title to or have any rights or claims over the products or services offered by you to the buyer.</li>
                        <li>At no time shall Maahir Bharat hold any right/title to or interest in the items nor have any obligations or liabilities with respect to such a contract. Maahir Bharat is not responsible for unsatisfactory or delayed performance of services, damages, or delays as a result of items which are out of stock, unavailable, or back-ordered.</li>
                        <li>The Platform is only a platform that can be utilized by you to reach a larger customer base to sell items or services. Maahir Bharat only provides a platform for communication and it is agreed that the contract for sale of any products or services shall be a strictly bipartite contract between you and the buyer.</li>
                        <li>You release and indemnify Maahir Bharat and/or any of its officers and representatives from any cost, damage, liability or other consequence of any of the actions of the users on the Platform and specifically waive any claims that you may have in this behalf under any applicable law. Notwithstanding its reasonable efforts on that behalf, Maahir Bharat cannot control the information provided by other users which is made available on the Platform. You may find other user's information to be offensive, harmful, inaccurate or deceptive. Please use caution and practice safe trading when using the Platform. Please note that there may be risks in dealing with underage persons or people acting under false pretence.</li>                   
                    </ol>
                    <li><b>Use of the Platform</b></li>
                    <p>You agree and understand that Maahir Bharat and the Platform merely provide hosting services to its registered users and persons browsing/visiting the Platform. All items advertised / listed and the contents therein are advertised and listed by registered users and are third party user generated contents. Maahir Bharat shall bear no responsibility or liability in relation to or arising out of third party user generated content. Maahir Bharat is merely an intermediary and does not interfere in the transaction between buyers and sellers.</p>

                    <p style="text-decoration: underline;">You agree, undertake and confirm that your use of the Platform shall be strictly governed by the following binding principles:</p>

                    <p><b>A.</b>You shall not host, display, upload, modify, publish, transmit, update or share any information or image which:
                    </p>
                    <p>(a) belongs to another person and over which you have no right;</p>
                    <p>(b) is grossly harmful, harassing, blasphemous, defamatory, bigotry, obscene, pornographic, paedophilic, libellous, invasive of another’s privacy, hateful, or racially, ethnically objectionable, disparaging, relating to or encouraging money laundering or gambling, or otherwise unlawful in any manner whatever, or unlawfully threatening or harassing, including but not limited to ‘indecent representation of women’ within the meaning of the Indecent Representation of Women (Prohibition) Act, 1986;</p>
                    <p>(c) is false, inaccurateor misleading in any way;</p>
                    <p>(d) is patently offensive to the online community, such as sexually explicit content or content that promotes obscenity, paedophilia, racism, bigotry, hatred, or physical harm of any kind against any group or individual;</p>
                    <p>(e) harasses or advocates harassment of another person;</p>
                    <p>
                        (f) involves the transmission of ‘junk mail’, ‘chain letters’, unsolicited mass mailing, or ‘spamming’; including spamming by ways of unrelated feedbacks on surveys
                    </p>
                    <p>(g) promotes illegal activity or conduct that is abusive, threatening, obscene, defamatory, or libellous;</p>
                    <p>
                        (h) infringes upon or violates any third party's rights [including but not limited to intellectual property rights, rights of privacy (including without limitation unauthorized disclosure of a person's name, email address, physical address, or phone number) or rights of publicity];
                    </p>
                    <p>
                        (i) promotes an illegal or unauthorized copy of another person's copyrighted work (see “Copyright complaint" below for instructions on how to lodge a complaint about uploaded copyrighted material) such as providing pirated computer programs or links, information to circumvent manufacturer-installed copy-protect devices, or pirated music or links to pirated music files;
                    </p>
                    <p>
                        (j) contains restricted or password-only access pages, hidden pages or images or URLs leading to any other pages (those not linked to or from another accessible page);
                    </p>
                    <p>
                        (k) provides material that exploits people in a sexual, violent or otherwise inappropriate manner or solicits personal information from anyone:
                    </p>
                    <p>
                        (l) provides instructional information about illegal activities such as making or buying illegal weapons, violating someone's privacy, providing or creating computer viruses;
                    </p>
                    <p>
                        (m) contains unauthorized videos, photographs or images of another person (whether a minor or an adult);
                    </p>
                    <p>
                        (n) tries to gain unauthorized access or exceeds the scope of authorized access to the Platform, profiles, blogs, communities, account information, bulletins, friend requests, or other areas of the Platform, or solicits passwords or personal identifying information for commercial or unlawful purposes from other users on the Platform;
                    </p>
                    <p>
                        (o) engages in commercial activities and/or sales such as contests, sweepstakes, barter, advertising, pyramid schemes, or the buying or selling of ‘virtual’ items related to the Platform without our prior written consent.<br>
                        Throughout the Terms, Maahir Bharat’s prior written consent means a communication coming from Maahir Bharat’s Legal Department in response to your request and specifically addressing the activities or conduct for which you have sought authorization;
                    </p>
                    <p>
                        (p) solicits gambling or engages in any gambling activity which we, at our sole discretion, believe is or could be construed as being illegal;
                    </p>
                    <p>
                        (q) interferes with another’s use and enjoyment of the Platform;
                    </p>
                    <p>
                        (r) refers to any website/URL which, at our sole discretion, contains material that is inappropriate for the Platform or any other website and content that is prohibited or violates the letter and spirit of Terms;
                    </p>
                    <p>
                        (s) harms minors in any way;
                    </p>
                    <p>
                        (t) infringes any patent, trademark, copyright, proprietary rights, third-party’s trade secrets, rights of publicity, or privacy, is fraudulent, or involves the sale of counterfeit or stolen items;
                    </p>
                    <p>
                        (u) violates any law for the time being in force;
                    </p>
                    <p>
                        (v) deceives or misleads the addressee/ users about the origin of messages or communicates any information which is grossly offensive or menacing in nature;
                    </p>
                    <p>(w) impersonates another person;</p>
                    <p>(x) contains software viruses or any other computer codes, files, or programs designed to interrupt, destroy, or limit the functionality of any computer resource; or contains any trojan horses, worms, time bombs, cancelbots, easter eggs, or other computer programming routines that may damage, detrimentally interfere with, diminish value of, surreptitiously intercept, or expropriate any system, data, or personal information;</p>
                    <p>(y) threatens the unity, integrity, defence, security or sovereignty of India, friendly relations with foreign states, or public order or causes incitement to the commission of any offence or prevents investigation of any offence or is insulting any other nation; offends the religious and national sentiments of the nation as included in ‘Zero Tolerance to Profanity, Hurting National and Religious Sentiments’ policy.</p>
                    <p>(z) shall, directly or indirectly, offer or attempt to offer trade or attempt to trade in any item which is prohibited or restricted in any manner under the provisions of any applicable law, rule, regulation or guideline for the time being in force;</p>
                    <p>(aa) shall create liability for us or cause us to lose (in whole or part) the services of our Internet Service Provider (“ISPs”) or other suppliers.</p>

                    <p><b>B. </b>
                        You shall not use any ‘deep-link’, ‘page-scrape’, ‘robot’, ‘spider’, automatic device, program, algorithm, methodology, or any similar or equivalent manual process to access, acquire, copy, monitor any portion of the Platform or content or in any way reproduce, or circumvent the navigational structure, presentation of the Platform, or any content to obtain or attempt to obtain any material, documents, or information through any means not purposely made available through the Platform. We reserve our right to bar any such activities.
                    </p>
                    <p><b>C. </b>
                        You shall not attempt to gain unauthorized access to any portion or feature of the Platform, other systems, networks connected to the Platform, server, computer, network, or the services offered on or through the Platform by hacking, password ‘mining’, or any other illegitimate means.
                    </p>
                    <p><b>D. </b>
                        You shall not probe, scan or test the vulnerability of the Platform or any network connected to the Platform or breach the security, authentication measures on the Platform or any network connected to the Platform. You may not reverse look-up, trace or seek to trace information on any other user of or visitor to Platform (including any account on the Platform that is not owned by you) or to its source or exploit the Platform, any service, information made available, or offered by or through the Platform in any way where the purpose is to reveal any information (including but not limited to personal identification or information other than your own information) provided by the Platform.
                    </p>

                    <p><b>E. </b>
                        You shall not make any negative, denigrating, or defamatory statement(s)/comment(s) about us, the brand name or domain name used by us, including the terms Maahir Bharat,  Maahir Bharat.com or otherwise engage in any conduct or action that might tarnish the image or reputation of Maahir Bharat or sellers on the platform or otherwise tarnish or dilute any Maahir Bharat trademark, service marks, trade name and/or goodwill associated with such trade, service marks or trade name as may be owned or used by us. You agree that you will not take any action that imposes an unreasonable or disproportionately large load on the infrastructure of the Platform or Maahir Bharat’s systems, networks, or any systems or networks connected to Maahir Bharat.
                    </p>
                    <p><b>F. </b>
                        You agree not to use any device, software or routine to interfere or attempt to interfere with the proper working of the Platform, any transaction being conducted on the Platform or any other person’s use of the Platform.
                    </p>
                    <p><b>G. </b>
                        You shall not forge headers or otherwise manipulate identifiers in order to disguise the origin of any message, transmittal you send to us on or through the Platform, or any service offered on or through the Platform. You may not pretend that you are or represent someone else or impersonate any other individual or entity.
                    </p>
                    <p><b>H. </b>
                        You may not use the Platform or any content for any purpose that is unlawful or prohibited by the Terms or to solicit the performance of any illegal activity or other activity which infringes the rights of Maahir Bharat and/or others.
                    </p>
                    <p><b>I. </b>
                        You shall at all times ensure full compliance with the applicable provisions of the Information Technology Act, 2000, and the other rules thereunder as applicable and amended from time to time and also all applicable domestic laws, rules and regulations (including the provisions of any applicable Exchange Control Laws or Regulations in force) and International Laws, Foreign Exchange Laws, Statutes, Ordinances and Regulations (including, but not limited to Integrated Goods and Services Tax Act, Central Goods and Services Tax Act, Food Safety and Standards Authority of India (FSSAI), relevant State Goods and Services Tax Act or Union Territories Goods and Services Tax Act and Custom Duty, Local Levies as may be applicable) and obtain the necessary licences and permits regarding your use of our Platform, service and/or tools and your listing, purchase, solicitation of offers to purchase, and sale of items or services. You shall not engage in any transaction in an item or service, which is prohibited by the provisions of any applicable law including exchange control laws or regulations for the time being in force. In particular you shall ensure that if any of your items listed on the Platform qualifies as an "Antiquity" or "Art treasure" as defined in the Act ("Artwork"), you shall indicate that such Artwork is "non-exportable" and sold subject to the provisions of the Antiquities and Art Treasures Act, 1972, and shall ensure that it is not delivered to any buyer at any place outside India.
                    </p>
                    <p><b>J. </b>
                        Solely to enable us to use the information you provide us with and so that we do not violate any rights you might have in your information, you agree to grant us a non-exclusive, worldwide, perpetual, irrevocable, royalty-free, and sub-licensable (through multiple-tiers) right to exercise the copyright, publicity or database rights or any other rights you have in your information for any current or future promotional or advertising related activities and any business purposes of Maahir Bharat.
                    </p>
                    <p><b>K. </b>
                        From time to time you shall be responsible for providing information relating to the items or services proposed to be sold by you. In this connection, you undertake that all such information shall be accurate in all respects. You shall not exaggerate or over emphasize the attributes of such items or services so as to mislead other users on the Platform in any manner.
                    </p>
                    <p><b>L. </b>
                        You shall not engage in advertising or solicitation of other sellers on the Platform to buy or sell any products or services, including but not limited to products or services related to what is displayed on the Platform. You may not transmit any chain letters or unsolicited commercial or junk email to other users acquired/via the Platform. It shall be a violation of the Terms to use any information obtained from the Platform in order to harass, abuse, or harm others or contact, advertise and sell to or solicit persons other than those who have chosen to buy from you. You understand that we have the right at all times to disclose any information (including the identity of the persons who have provided information or material on the Platform) as necessary to satisfy any law, regulation, or valid governmental request. This may include, without limitation, disclosure of the information in connection with the investigation of an alleged illegal activity or its solicitation and/or response to a lawful court order or subpoena. In addition, we can (and you hereby expressly authorized us to) disclose any information about you to law enforcement or other government officials as we, at our sole discretion, deem necessary or appropriate in connection with the investigation and/or resolution of possible crimes, especially those that may involve personal injury. We reserve the right, but have no obligation, to monitor the material posted on the Platform. Maahir Bharat shall have the right, at its sole discretion, to remove any content that violates or is alleged to violate any applicable law or either the spirit or letter of the Terms. Notwithstanding this right, YOU REMAIN SOLELY RESPONSIBLE FOR THE CONTENT OF THE MATERIAL YOU POST ON THE WEBSITE AND YOUR INDEPENDENT COMMUNICATION WITH THE BUYERS AND OTHER SELLERS, REGARDLESS OF FORM. Please be advised that such content posted does not reflect Maahir Bharat’s views. In no event shall Maahir Bharat assume or have any responsibility or liability for any content posted on the Platform or claims, damages, or losses resulting from its use and/or appearance of it on the Platform. You hereby represent and warrant that you have necessary rights to all the content you provide and all information it contains and that such content shall not infringe any proprietary or other rights of third parties or contain any misleading, libellous, tortious, or otherwise unlawful information.
                    </p>
                    <p><b>9. </b>
                        Your correspondence or business dealings with or participation in the promotion of advertisers on or through the Platform (including payment and delivery of related products or services, any other terms, conditions, warranties, or representations associated with such dealings) are solely between you and such advertisers. We shall not be responsible or liable for any loss or damage of any sort incurred as a result of such dealings or the presence of such advertisers on the Platform.
                    </p>
                    <p><b>10. </b>
                        It is possible that other users (including unauthorized persons or ‘hackers’) may post or transmit offensive or obscene material on the Platform and that you may be involuntarily exposed to such material. It is also possible for others to obtain personal information about you due to your use of the Platform and use such information to harass or injure you. We do not approve of such unauthorized uses but by using the Platform, you acknowledge and agree that we are not responsible for the use of any personal information that you publicly disclose or share with others on the Platform. Please carefully select the type of information that you publicly disclose or share with others on the Platform.
                    </p>
                    <p><b>11. </b>
                        Maahir Bharat shall have all the rights to take necessary action and claim damages that may occur due to your involvement/participation in any way on your own or through group(s) of people, intentionally or unintentionally, in DoS (denial of service) / DDoS (Distributed Denial of Services).
                    </p>
                    <p><b>12. </b>
                        Maahir Bharat and/or its affiliates may from time to time in partnership/association with its partners and/or third-party sponsors, organise/enable promotional campaigns on the Platform for the benefits of the customers/Sellers. Partners/third party sponsors may prescribe certain objective qualifying criteria to identify Sellers who will be eligible for the benefits of the campaign. All Sellers who qualify based on the objective criteria provided by such sponsors of the campaign will be auto opted-in and be able to obtain the benefits of such promotional campaign. In the event any Seller does not qualify based on the objective criteria, Sellers may choose to participate in such campaigns by expressly opting-in for them. In the event a Seller opts in for such promotional campaigns that they are not eligible for to enhance their sales, they will have to bear the cost of such promotional campaigns, if any, limited to the sales of their products. For avoidance of any doubt, some Sellers may qualify, and some may not, based on the qualifying criteria set for each individual campaign. Please refer to the campaign communication/notifications for more details, as may be communicated to you from time to time.
                    </p>
                    <p><b>13. Selling</b><br>
                        As a registered seller, you shall list item(s) for sale on the Platform in accordance with the policies which are incorporated by way of reference in this Terms. You must be legally able to sell the item(s) you list for sale on our Platform and must have all the necessary licences and permits required for such sale. You must ensure that the listed items do not infringe upon the intellectual property, trade secret or other proprietary rights or rights of publicity or privacy rights of third parties. Listings may only include text descriptions, graphics, pictures or videos that describe your item for sale. All items must be listed in an appropriate category on the Platform. All listed items must be kept in stock for successful fulfilment of sales. The listing description of the item must not be misleading and must describe the actual condition of the product. If the item description does not match the actual condition of the item, you agree to refund any amount that you may have received from the buyer. You agree not to list a single product in multiple quantities across various categories on the Platform. Maahir Bharat reserves the right to delete such multiple listings of the same product listed by you in various categories. Maahir Bharat reserves the right to restrict the selling of products originating from certain countries. For Food and Nutrition category, seller shall adhere to the minimum balance shelf life norms as provided at the link<a>here</a>
                    </p>
                    <p><b>14. Compliance on selling of goods/services</b><br>
                        You shall also ensure full compliance with the provisions of Integrated Goods and Services Tax (IGST), Central Goods and Services Tax (CGST) and Union Territory Goods and Services Tax (UTGST) or State Goods and Services Tax (SGST) in respect of the goods/services supplied by you.

                    </p>
                    <p>
                        It is your responsibility to charge appropriate goods and services taxes on the supplies effected and remittance of the same to the Government. Maahir Bharat shall not be responsible for any deficiency and/ or omission on your part.
                    </p>
                    <p>
                        Pursuant to the tax collection at source provisions under IGST, CGST and/UTGST or SGST, the portal would collect tax collection at source at applicable rates on net value of taxable supplies made through the portal and remit to the appropriate Government.
                    </p>
                    <p>
                        In case of any mismatches on account of tax collection at source, you shall be required to provide all relevant information to Maahir Bharat to correspond with the relevant authorities and also in case of any liability accruing on account of omission shall be your obligation to pay such deficit.
                    </p>
                    <p>
                        You shall also be required to provide your GSTIN , without which we will not be able to raise an invoice on you. In the event that you do not provide your GSTIN number, transactions on your account will be blocked and orders will not be processed on your account.
                        <span style="font-style: italic;">In the event of you providing your Input Service Distributor Registration Number, Maahir Bharat would be issuing an invoice to the ISD GST registration number as furnished by you. It is your responsibility to undertake the necessary compliance required in respect of the said ISD registration number.</span>
                    </p>
                    <p>
                        In the event of any conflict between the terms of this clause and any other clause in these terms of use, the provisions of this clause will prevail. We do not mandate that any of your Products should be sold exclusively on the Platform. Maahir Bharat unilaterally waives any obligation on You to sell exclusively on the Platform. Any written or oral arrangements to the contrary, shall stand unilaterally waived.
                    </p>
                    <p style="text-decoration:underline;">
                        As per Section 194-O of the Finance Act, 2020, Maahir Bharat will deduct TDS on the gross amount of sale (excluding GST) of goods or provision of services provided through the Platform at 0.75% from October 1, 2022 to March 31, 2023 and at 1% thereafter.
                    </p>

                    <p><b>15. Content Posted on the Platform</b><br>
                        All text, graphics, seller interfaces, visual interfaces, photographs, trademarks, logos, sounds, music and artwork, notes, messages, emails, billboard postings, drawings, profiles, opinions, ideas, images, videos, audio files, other material or information (collectively ‘Content’) are third-party generated Content and Maahir Bharat has no responsibility or liability over such third-party generated Content as Maahir Bharat is merely an intermediary for the purposes of this Terms. Except as expressly provided in the Terms, no part of the Platform including the Content may be copied, reproduced, republished, uploaded, posted, publicly displayed, encoded, translated, transmitted or distributed in any way (including ‘mirroring’) to any other computer, server, website or other medium for publication, distribution or any commercial enterprise without Maahir Bharat’s prior written consent.
                    </p>
                    <p>
                        You may use the information on the products and services made available on the Platform for downloading provided you:
                    </p>
                    <p>
                        (1) do not remove any proprietary notice language in all copies of such Content;
                    </p>
                    <p>(2) use such Content only for your personal, non-commercial informational purpose and do not copy or post such information on any networked computer or broadcast it to any media;</p>
                    <p>(3) make no modifications to any Content; and</p>
                    <p>(4) do not make any additional representations or warranties relating to the Content.</p>

                    <p>You shall be responsible for the Content posted or transmitted on the Platform by You. The Content will become our property and you grant us the worldwide, perpetual, royalty free and transferable rights in such content. We shall be entitled to, consistent with our privacy policy as adopted in accordance with applicable law, use the Content or any of its elements for any type of purpose forever, including, but not limited to, promotional and advertising purposes in any media, whether now known or hereafter devised or the creation of derivative work. You agree that any content you post may be used by us, consistent with this TERMS, and you are not entitled to any payment or other compensation for such use.</p>

                    <p><b>16. Limited License</b><br>
                        Maahir Bharat grants sellers a limited, non-transferable, non-exclusive, non-sub licensable, non-assignable and personal license to use "Powered by Maahir Bharat" and/or “Maahir Bharat.com” name and/or logo on seller’s invoice for transactions concluded on the Platform and on packing material used by sellers for delivery of Products sold on the Platform.<br> Maahir Bharat reserves the right to revise the categories, criteria, and benefits to promote healthy competition amongst the sellers so that their performance lead to better customer experience on the Platform.
                    </p>
                    <p><b>17. Payment</b></p>

                    <p>1. Transactions, transaction price and all commercial terms such as delivery, dispatch of products and/or services are as per principal to principal bipartite contractual obligations between sellers and buyers and the payment facility is merely used by sellers and buyers to facilitate the completion of transactions. Use of the payment facility shall not render Maahir Bharat liable or responsible for non–delivery, non-receipt, non-payment, damage, breach of representations and warranties, non-provision of after-sales or warranty services or fraud as regards the products and/or services listed on the Platform.</p>
                    <p>
                        2. You have specifically authorized Maahir Bharat or its service providers to collect, process, facilitate, and remit payments and/or the transaction price electronically or through cash on delivery (COD) to and from buyers in respect of transactions through payment facility. Your relationship with Maahir Bharat is on a principal to principal basis and by accepting the Terms, you agree that Maahir Bharat is an independent contractor for all purposes and does not have control of or liability for the products or services that are listed on the Platform and paid for by using the payment facility. Maahir Bharat does not guarantee the identity of any User nor does it ensure that a buyer or a seller will complete a transaction.
                    </p>
                    <p>
                        3. You understand, accept, and agree that the payment facility provided by Maahir Bharat is neither a banking nor financial service, but merely a facilitator providing an electronic, automated online electronic payment facility for receiving payment, or cash on delivery (COD) payment, collection and remittance for transactions on the Platform using the existing authorized banking infrastructure and credit card payment gateway (PG) network. Further, by providing payment facility, Maahir Bharat neither acts as a trustee nor fiduciary with respect to transaction or transaction price.
                    </p>
                    <p><b>It is hereby clarified that cash on delivery (COD) option may not be available for select products or categories, at Maahir Bharat’s sole discretion.</b></p>
                    <p><b>4.</b>
                        All online bank transfers from valid bank accounts are processed using the gateway provided by the respective issuing bank that supports payment facility to provide these services to the users. All such online bank transfers on payment facility are also governed by the terms and conditions agreed to between a seller buyer and the respective issuing bank.
                    </p>
                </ol>

                    <h5>18. Dispatch of products and/or services</h5>
                    <p>1.You, as a seller, shall be required to dispatch the products and/or services for every transaction to the buyer within the time period as provided in the TERMS to ensure that the products and/or services are delivered in a timely manner. Further, you will solely be responsible for undertaking transit insurance for products sold by You on the Platform. For avoidance of doubt, Maahir Bharat will not be responsible for undertaking any insurance(s) for products sold by sellers on the Platform</p>
                    <p>2. Seller shall provide dispatch details and details of after-sales services related to products and services listed by it on the Platform to Maahir Bharat in such a manner and within a time period as provided in the policies, failing which the transaction shall stand cancelled.</p>

                    <p>3. Seller shall dispatch the products and/or services using only an approved delivery channel which provides appropriate ‘proof of dispatch’ & ‘proof of delivery’ (PoDs) documentation. Such PoD documentation relating to delivery should be maintained by a seller for a period of 3 (three) years from the date of dispatch. The PoDs should be furnished to Maahir Bharat on demand within the time frame as notified from time to time.</p>
                    <p>4. Seller agrees that the dispatch details shall be true, correct, and duly authorized and shall not be misleading, fraudulent, false, unauthorized, illegal and shall not contain any misrepresentation of facts.</p>
                    <p>5. In case a seller fails to provide dispatch details or provides dispatch details not complying with policies, it shall result in consequences as more specifically stated in the TERMS and may lead to suspension and/or termination of seller account.</p>
                    <p>6. Seller agrees that the transaction price paid by a buyer will be remitted to a seller’s bank account contingent upon the following events:</p>
                    <p>
                        a) Buyer confirms the delivery of products and/or services in the transaction;
                    </p>
                    <p>b) Buyer does not take any action on payment facility to confirm delivery within such a time period as provided in the policies despite confirmation of dispatch of products and/or services by a seller to the buyer;</p>
                    <p>
                        c) Buyer’s refund claim is rejected by Maahir Bharat due to any breach of the Terms, policies, and any applicable law;
                    </p>
                    <p>Once the transaction is completed by the Seller, the remittance to seller shall be made in accordance with RBI Intermediary Guidelines.</p>
                    <p>7. You are required to route all shipments/consignments through the Logistic Partner, unless otherwise specified. ‘Logistic Partner’ shall mean a logistic service provider as approved by Maahir Bharat.</p>

                    <h5>19. Prepaid Payment Instruments</h5>
                    <p>Maahir Bharat may, either itself or through third-party service providers, offer prepaid instruments as a payment option for transactions on the Platform to users. Any purchases by buyers on the Platform using the prepaid instruments shall be governed by the following terms and conditions:
                    </p>
                    <p>1. Such prepaid instruments may be used to make payments for the products and/or services purchased on the Platform</p>  

                    <p>2. Such prepaid instruments can be redeemed by buyers by selecting the payment mode as may be provided on the Platform.</p> 
                    <p>3. Such prepaid instruments cannot be used to purchase other prepaid instruments or gift vouchers.</p>
                    <p>4. If the order value exceeds the amount of such prepaid instruments, the balance must be paid by the respective buyer via Credit Card/Debit Card /Internet Banking. COD shall not be available as payment option for such transactions.</p>
                    <p>5. If the order value is less than the amount of such prepaid instruments, the outstanding balance (after deduction of order value) will reflect as credit balance for such prepaid instruments.</p>
                    <p>6. Prepaid instruments and any unused balance of such prepaid instruments shall expire 1 year from the date of their issue.</p>
                    <p>7. Prepaid instruments cannot be redeemed for cash.</p>
                    <p>8. Maahir Bharat is not responsible if prepaid instruments are lost, stolen, or used without permission.</p>
                    <p>9. Buyers can combine and use a maximum of 3 prepaid instruments per order. They can be combined with promotional codes.</p>
                    <p>10. Purchases of prepaid instruments are not eligible for cashback offers.</p>
                    <p>11. All sellers on the Platform will accept this prepaid instrument as a payment instrument.</p>
                    <p>12. Maahir Bharat will make payments to sellers whose products and/or services have been purchased by buyers redeeming electronic gift vouchers (EGV) as per the guidelines issued by the Reserve Bank of India from time to time.</p>
                    <h5>20. Financial Facilities for customers</h5>
                    <p>Maahir Bharat has operationalized tie-ups with multiple partners for providing financial assistance to customers for purchasing products on the platform and thereby enhancing the transaction capability of customers. In pursuance of the same, in the event of the customers opting for the financial assistance program and you duly receiving such amounts from the partners (on behalf of the customers), you hereby agree to assign all receivables from the customer for such transaction. Therefore you hereby agree that without any further action on your part, upon receipt of the amount due from such partners, any and all receivables due from the customers shall stand assigned in favour of the partner. You hereby authorize Maahir Bharat to enter into any documentation on your behalf to complete and perfect the assignment. Upon such assignment, the financing partner shall have all the rights as the seller may have had in relation to the collection of receivables from the customer and the customer shall be required to repay the financing partner directly. The lending partner further reserves the right to assign and transfer such receivables under these terms and conditions to an NBFC/financial institution as it may deem fit.</p>
                    <h5>21. Charges</h5>
                    <p><b>GST /Taxes:</b>
                        You are responsible for paying all fees associated with the use of the Platform and charges collected in respect of such usage. You agree to bear any and all applicable taxes, charges, cesses levied thereon (including CGST+SGST/IGST/CGST+UGST and GST cess as may be applicable to the transaction).
                    </p>
                    <p>a. A seller agrees that Maahir Bharat may offer to provide express remittance to eligible sellers as per payments settlement policy. Express Remittance shall be subject to RBI Intermediary Guidelines and arrangements/directions of the nodal bank. Maahir Bharat, at its sole discretion, may make such an offer to eligible sellers and the same shall not be construed as a right but only as a privilege. Eligible sellers understand that Maahir Bharat reserves the right to withdraw Express Remittance at any time for any violation of the Terms or Maahir Bharat’s policies and/or failure by the eligible sellers to maintain or comply with the parameters as may be decided by Maahir Bharat from time to time.</p>
                    <p>b. Invoice generation: A seller expressly agrees that issuing correct and complete invoice is the sole and primary responsibility of a seller. We will assist you with this process by generating an invoice on your behalf.For us to generate these invoices, we would need a digital image of your signature which will be affixed on the invoice. The invoice shall then be generated and sent to the seller. The seller shall be required to physically sign the invoice, print the invoice and affix the same on the consignment. The invoice generated by Maahir Bharat shall be affixed by the seller on the consignment. Notwithstanding anything else contained in these terms of use, the seller shall be solely liable for any liability which may be imposed by taxation authorities for any discrepancy in the invoices.</p>
                    <p>A seller expressly agrees that issuing the correct and complete invoice is the sole and primary responsibility of a seller. Furthermore, the seller shall ensure that invoices state ‘Powered by Maahir Bharat’ and failing to do so, a seller shall be liable to chargebacks (as applicable).</p>
                    <p>c. In case of any chargebacks levied by the bank, Maahir Bharat shall have the right to deduct such chargebacks from seller remittances, present and future, and a seller’s only remedy will be to discuss and resolve the same with the bank. A seller hereby agrees to extend full co-operation in resolving the chargeback disputes raised by a buyer through the bank and shall provide necessary documentation regarding the transaction to the complete satisfaction of the bank. In case the chargeback is ruled against a seller, Maahir Bharat shall be entitled and authorized to recover the same from the seller to its fullest extent and the bank’s decision shall be final and binding in this regard. In the event Maahir Bharat has made any excess payment to the seller inadvertently, such excess payments shall be set-off from any future payments payable by Maahir Bharat to the seller.</p>
                    <p>d. Maahir Bharat may delay notifying the payment confirmation, i.e. informing the seller to dispatch if Maahir Bharat deems suspicious or a buyer conducts high transaction volumes to ensure safety of the transaction and transaction price. In addition, Maahir Bharat may hold transaction price and not inform seller to dispatch or remit transaction price to law enforcement officials (instead of refunding the same to a buyer) at the request of law enforcement officials or in the event of a buyer being engaged in any form of illegal activity.</p>
                    <p>e. Sellers acknowledge that Maahir Bharat will not be liable for any damages, interests, claims etc. resulting from not processing a transaction/transaction price or any delay in processing a transaction/transaction price that is beyond the control of Maahir Bharat.</p>
                    <p>f. Maahir Bharat shall make payments into the bank account provided by a seller during the seller registration process. Once Maahir Bharat has made payments into such a bank account number, Maahir Bharat shall be discharged of any/all liabilities towards the seller and the seller shall not be eligible for any claims whatsoever.</p>

                    <h5>22. Compliance with Laws:</h5>
                    <p>1.Seller shall sign anundertakingstating that they have obtained and will continue to maintain in force all the necessary legal provisions, regulations, licenses, permissions, authorizations, and permits needed to distribute, market, supply and sell the “Products” on www.Maahir Bharat.com under applicable laws, and Standards Regulations along with amendments therein, from time to time. For all times during which the seller may advertise, distribute, market, supply or sell the Products on www.Maahir Bharat.com, the undertaking remains true and correct in all respects. Further, the seller shall immediately notify Maahir Bharat, in writing, upon the lapse of the concerned License and/or in case of receipt of any order, demand, warrant or document or any regulatory action with respect to the said License. The seller acknowledges and agrees that Maahir Bharat shall be permitted to assign or otherwise furnish the undertaking to any authority or person as may be required for official purposes. Seller shall also comply with the Legal Metrology Act, 2009 and the related rules and regulations while listing products on the platform Maahir Bharat.com. Seller shall be required to enter the mandatory attributes while listing products on the platform (including but not limited to the country of origin of the product) as provided under the Legal Metrology Packaged Commodity Rules and the related amendments.</p>
                    <p>2. In the event of sale of jewellery, the seller shall provide a hallmark certificate (in accordance with applicable laws) along with the product at the time of delivery. Further, it shall be sole responsibility of the Seller to comply with hallmarking or other similar provisions applicable for the sale of jewellery and Maahir Bharat shall not be liable whatsoever for any non-compliance in this regard.</p>
                    <p>3. In the event of sale of jewellery, Seller shall ensure conducting of buyer KYC in accordance with the prevention of anti-money laundering laws and other applicable laws. Maahir Bharat hereby disclaims any responsibility for conducting Buyer KYC.</p>
                    <p>4. Seller shall comply with all laws and regulations applicable, including but not limited to anti-money laundering (including ‘know your customer’ and ‘customer due diligence’), and economic sanctions laws and regulations. Neither party will engage in a transaction pursuant to this Terms that will cause the other party to violate such regulations.</p>
                    <p>5. Seller shall ensure that no products are sourced or used in the manufacturing or in the provision of services which originate wholly or in part, from any of the prohibited countries stated in the ‘OFAC Regulations and Other Applicable Sanctions Regulations’.</p>
                    <p>6. If and to the extent that you collect, access, use, store, record, or otherwise process (collectively “Process”) any personally identified or identifiable information such as name, age, gender, email address, physical address, phone number, in any form that can be linked to a specific individual (“Personal Information”) received by you from or on behalf of Maahir Bharat (or any Maahir Bharat group company) employees, contractors, users, partners, or other third parties or otherwise obtained in connection with performing your obligations under this Terms (“Maahir Bharat’s Personal Information"), you agree to:</p>
                    <p>
                        <ol type="i" style="padding-left: 35px;"><li>
                        comply with applicable data protection laws, rules and regulationsgoverning the collection, use, protection, breach notification, retention, disclosure of Personal Information including but not limited to Information Technology Act, 2000 and the Information Technology (Reasonable Security practices and procedures and sensitive personal data or information) Rules, 2011 (“Applicable Data Protection Law”), including any requirements applicable to storage or cross-border transfer of Personal Information outside India;
                        </li>
                        <li>keep and maintain all Maahir Bharat’s Personal Information in strict confidence and the obligation to protect Personal Information shall survive in perpetuity; and</li>
                        <li>Process Maahir Bharat’s Personal Information solely to fulfil Your obligations under this Terms and not sell, rent, trade, lease, use for its own advertisement or marketing purposes,or otherwise make an unauthorized disclosure of Maahir Bharat’s Personal Information to any third party.</li>
                        </ol>
                    </p>
                    <p>
                        7. If and to the extent that you provide yours or others’ Personal Information to Maahir Bharat for processing, you warrant that such Personal Information was collected lawfully, and there is no restriction on you under the Applicable Data Protection Law, from providing such Personal Information to Maahir Bharat or any processing by Maahir Bharat under this Terms. We will only use information provided by you in accordance with this Terms and our Privacy Policy available at <a href="#"> www.maahirbharat.com.</a>
                    </p>
                    <p>8. You undertake sole and exclusive responsibility to ensure that the products you want to list on www.maahirbharat.com for Sales are permissible for such a Sale and are not prohibited or restricted per one or many conditions imposed by the extant laws of the land, Maahir Bharat’s Prohibited and Restricted Items Policy, or other Maahir Bharat policies/Indian Laws listed.</p>
                    <p>9. Products must adhere to the legal metrology laws and Indian Labelling requirements by ensuring that the indicated weights and measurement indicated in the products and/or its components are commensurate with the mandatory and legal requirements of the same which make the product and/or components accurate, authentic and secure for consumption/utilisation by the customer. Maahir Bharat does not assume any responsibility for the proceedings undertaken by an aggrieved customer/consumer against the seller in the event of a non-adherence. However, in the event of a complaint from a consumer/customer, the seller is obligated to answer queries on the non-adherence to the Legal Metrology Laws, failing which Maahir Bharat can temporarily/indefinitely suspend/terminate/block/with-hold your account at its own discretion.</p>
                    <h5>23. Product Description</h5>
                    <p>Maahir Bharat does not warrant that product description or other content on the Platform is accurate, complete, reliable, current, or error-free and assumes no liability in this regard.</p>
                    <h5>24. Audits</h5>
                    <p>Maahir Bharat shall have the right to inspect and audit seller’s records and premises / place of business through itself or through Maahir Bharat approved third party testing agencies. Cost of such an audit shall solely be borne by Maahir Bharat unless the audit reflects discrepancy in seller accounts / non-compliance with Maahir Bharat’s seller policies, in which case the cost of audit shall be borne by the seller.</p>

                    <h5>25. Breach</h5>
                    <p>Without limiting other remedies, we may limit your activity, immediately remove your information, warn other users of your actions immediately, temporarily/indefinitely suspend/terminate/block your account and/or refuse you access to the Platform, or put your account on hold, in the event of, including but not limited to, the following:</p>
                    <p>1. if you breach the Terms, privacy policy or other policies (if any);</p>
                    <p>2. if we are unable to verify or authenticate any information you provide;</p>
                    <p>3. if it is believed that your actions may cause legal liability for you, other users, or us; or</p>
                    <p>4. if you do not produce the legal requirement documents such as, the documents required for product sales in the Drugs and Cosmetics category, the BIS license documents, the Brand Authorisation letter, or a Trademark registration proof, as may be required by Maahir Bharat Authorities.</p>

                    <h5>26. Termination.</h5>
                    <p>In addition to any remedies that may be provided under these Terms and Conditions, Maahir Bharat may terminate this Contract with immediate effect upon written notice to you, if seller: (i) fails to pay any amount when due under this Contract and such failure continues for thirty (30) days after receipt of written notice of non-payment; (ii) has not otherwise performed or complied with any of these Terms and Conditions, in whole or in part; or (iii) becomes insolvent, files a petition for bankruptcy or commences or has commenced against it proceedings relating to bankruptcy, receivership, reorganization or assignment for the benefit of creditors.</p>

                    <h5>27. Amendment and Modification.</h5>
                    <p>These Terms and Conditions may only be amended or modified in a writing which specifically states that it amends these Terms and Conditions and is signed by an authorized representative of each party.</p>

                    <h5>28. Waiver.</h5>
                    <p>No waiver by Seller of any of the provisions of this Contract is effective unless explicitly set forth in writing and signed by Seller. “No seller shall by any act of delay, indulgence, omission, or otherwise be deemed to have waived any right or remedy hereunder or to have acquiesced in any default or event of default.”No failure to exercise, or delay in exercising, any right, remedy, power or privilege arising from this Contract operates, or may be construed, as a waiver thereof.</p>

                    <h5>29. Termination</h5>
                    <p>We may at any time, at our sole discretion, reinstate suspended sellers. A seller that has been suspended or blocked may not register or attempt to register with us or use the Platform (through itself or any other entity or legal form) in any manner whatsoever until such time that such a seller is reinstated by us. Notwithstanding the foregoing, if you breach the Terms or other rules and policies, we reserve the right to recover any amounts due and owed by you to us and take strict legal action, including but not limited to a referral to the appropriate police or other authorities for initiating criminal or other proceedings against you.</p>

                    <h5>30. Indemnity</h5>
                    <p>You shall indemnify and hold harmless Maahir Bharat its owner, licensee, affiliates, subsidiaries, group companies (as applicable) and their respective officers, directors, agents, and employees from any claim, demand, or actions including reasonable attorneys' fees made by any third party or penalty imposed due to or arising out of your breach of the Terms, privacy policy and other policies or your violation of any law, rules, regulations or the rights (including infringement of intellectual property rights) of a third party.</p>

                    <h5>31. Trademark complaint</h5>
                    <p>Maahir Bharat respects the intellectual property of others. In case you feel that your trademark has been infringed, you can write to Maahir Bharat at <a href="mailto:maahirbharat@gmail.com.">maahirbharat@gmail.com.</a> or raise an incident from your seller dashboard</p>

                    <h5>32.Trademark, Copyright and Restriction</h5>
                    <p>The Website is controlled and operated by Maahir Bharat and products are sold by respective registered sellers. All material on the Platform, including images, illustrations, audio clips, and video clips, are protected by copyrights, trademarks and other intellectual property rights. You must not copy, reproduce, republish, upload, post, transmit, or distribute Maahir Bharat’s or other sellers’ material in any way, including by email or other electronic means and whether, directly or indirectly, you must not assist any other person to do so. Without the prior written consent of the owner, modification or use of the material on any other website/networked computer environment or for any purpose other than personal, non-commercial use is a violation of the copyrights, trademarks, and other proprietary rights is prohibited. Any use for which you receive any remuneration, whether money or otherwise, is a commercial use for the purposes of this clause.</p>

                    <h5>33.Limitation of Liability</h5>
                    <p>IN NO EVENT SHALL MAHIR BHARAT BE LIABLE FOR ANY SPECIAL, INCIDENTAL, INDIRECT, OR CONSEQUENTIAL DAMAGES OF ANY KIND IN CONNECTION WITH THE TERMS, EVEN IF MAAHIR BHARAT HAS BEEN INFORMED IN ADVANCE OF THE POSSIBILITY OF SUCH DAMAGES.</p>

                    <h5>34.Applicable Law</h5>
                    <p>The Terms shall be governed, interpreted, and construed in accordance with the laws of India. The place of jurisdiction shall exclusively be Pune.</p>

                    <h5>35.Jurisdictional Issues/Sale in India Only</h5>
                    <p>Unless otherwise specified, the material on the Website is presented solely for the purpose of sale in India. Maahir Bharat makes no representation that the material on the Website is appropriate or available for use in other locations/countries other than India. Those who choose to access the Website from other locations/countries other than India do so on their own initiative and Maahir Bharat is not responsible for supply of products/refund for the products ordered from other locations/countries other than India and compliance with local laws, if and to the extent local laws are applicable.</p>

                    <h5>36.Contact Us</h5>
                    <p>Please send any comments or questions, including all enquiries by raising an incident from your seller dashboard.</p>

                    <h5>37.Grievance Officer</h5>
                    <p>In accordance with the IT Act, 2000, and the rules thereunder, the name and contact details of the grievance officer are provided below:</p>
                    <p>Xyz ------ </p>
                    <p>Mrs. Bharti Chauhan</p>
                    <p>Maahir Bharat Ecom portal, under ABC training solutions, </p>
                    <p>S_ 14, Super Mall, Salunkhe Vihar Road,</p>
                    <p>Pune - 411040</p>
                    <p>Email: <a href="mailto:maahirbharat@gmail.com">maahirbharat@gmail.com</a></p>
                    <p>xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx</p>
            </div>

        </div>

    </div>
@endsection


@push('styles')
@endpush